spring.application.name=object-accounting-service
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
logging.level.liquibase=INFO
logging.level.liquibase.executor=INFO

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

server.port=8090
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
logging.level.org.springdoc=DEBUG

minio.endpoint=${MINIO_URL}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket.contracts=contracts
minio.bucket.pprs=pprs
minio.bucket.objects=objects
minio.file.max-size.pdf=52428800
minio.file.max-size.image=10485760

keycloak.url=${KEYCLOAK_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
